# Generated by Django 5.0.4 on 2024-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_carphoto_car_other_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='car',
        ),
    ]
