# Generated by Django 5.0.4 on 2024-04-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_carphoto_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='other_photos',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.car'),
            preserve_default=False,
        ),
    ]
