# Generated by Django 5.0.4 on 2024-04-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_car_other_photos_carphoto_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.car'),
        ),
    ]
