# Generated by Django 5.0.4 on 2024-04-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240408_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='blog.car'),
            preserve_default=False,
        ),
    ]
