# Generated by Django 5.0.4 on 2024-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
