# Generated by Django 5.0.4 on 2024-04-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_booking'),
        ('bookings', '0002_cars_delete_car_remove_booking_car_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.car'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
