# Generated by Django 5.0.4 on 2024-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_period_start_alter_busydate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='busydate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
