# Generated by Django 5.0.4 on 2024-05-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_car_alter_booking_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnavailableDate',
        ),
    ]
